### ISSUE TITLE
Change keybinds?

### ISSUE THREAD

**Issue by corrupt3d** [gunrun66/Scooby#1]
Is there a way I can go into the files and change the keybinds? and Velocity is way to noticeable. You never get any knockback.

**Comment by gunrun66** [comment]
Working on it as I post this.

**Comment by gunrun66** [comment]
Just finished adding customizable key binds. They are saved in: <your_minecraft_directory>/opencomputers/key_binds.cfg

**Comment by gunrun66** [comment]
I will add a way to customize Velocity's knockback multipliers tomorrow, I need to go to bed :ghost: .

**Comment by corrupt3d** [comment]
@gunrun66 Im currently testing the keybinds, but when I try to keybind triggerbot it says "cannot bind mode TriggerBot to key R because it does not exist"

**Comment by gunrun66** [comment]
Added a way to customize Velocity. I will push the commit once I fix a few more things.
