### ISSUE TITLE
spelling

### ISSUE THREAD

**Issue by TheBiblMan** [gunrun66/Scooby#2]
you spelt mod wrong fucktard

thanks.

**Comment by corrupt3d** [comment]
atleast if works.

**Comment by TheBiblMan** [comment]
thats probably the worst programming mentality in the world right there

**Comment by corrupt3d** [comment]
Well some people don't want their coding to be readable so they make it another language. So how is that the wrong mentality?

**Comment by TheBiblMan** [comment]
the mentality of "it works, it's good enough"
the client is clearly in written in english
mode -> mod

**Comment by gunrun66** [comment]
@TheBiblMan NO U

I miss seeing your HF posts. They made me lol. W0t happened d00d?

**Comment by TheBiblMan** [comment]
got bored, 99% of the people are just skids and when you're the top predator of the food chain, it gets boring without competition
igcses atm so gotta work

**Comment by gunrun66** [comment]
Closing this to not have the issue notification there. Sorry Bibl :ghost:
