### ISSUE TITLE
[Suggestion] A simple ESP

### ISSUE THREAD

**Issue by NIGGR** [gunrun66/Scooby#4]
This version of Scooby is almost perfect, good job Gunrun, In my opinion, the only thing the client needs at this moment is a very simple ESP/Tracers cheat, maybe with color distance.
I already tried to make one, but due to my lack of java/forge knowledge i failed hard.

**Comment by gunrun66** [comment]
Sorry, I'm not going to add that because this is a ghost client. Adding that would be way too obvious. The point of a ghost client is to be able to record/screenshare without being caught.

**Comment by NIGGR** [comment]
Togglable? Lol
