### ISSUE TITLE
Triggerbot does not disable on death

### ISSUE THREAD

**Issue by heroinisthebest** [gunrun66/Scooby#7]
Also you can still sprint into blocks

**Comment by gunrun66** [comment]
What do you mean? I just tested if TriggerBot disables on death and it does... In regards to Sprint, I don't see what's wrong with it. I literally made it check the same stuff that vanilla Minecraft checks for sprinting.

**Comment by heroinisthebest** [comment]
whoops sorry I must have pressed the bind again
